version: 2
jobs:
  build:
    working_directory: /tilewarm
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/tilewarm.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/tilewarm.tar | true
      - run:
          name: Build app Docker image
          command: |
            docker build --cache-from=life360/tilewarm -t life360/tilewarm .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/tilewarm.tar tilewarm
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/tilewarm.tar
      - run:
          name: Push tilewarm Docker image
          command: |
            echo $DOCKER_USER
            TAG=latest
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
               docker push life360/tilewarm:$TAG
            fi
