version: 2
jobs:
  build:
    working_directory: /tilewarm
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build app Docker image
          command: |
            docker build --cache-from=life360/tilewarm -t life360/tilewarm .
      - run:
          name: Push tilewarm Docker image
          command: |
            echo $DOCKER_USER
            TAG=latest
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
               docker push life360/tilewarm:$TAG
            fi
